# Generated by Django 4.2 on 2023-04-14 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0002_alter_branch_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='tree_menu.branch'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
